#!/usr/bin/env python

import sys, urllib2, ConfigParser

config = ConfigParser.ConfigParser()
config.read("~/.config/.pychube")

opener = urllib2.build_opener(urllib2.HTTPHandler)
if sys.stdin.isatty():
	request = urllib2.Request('http://www.pachube.com/api/'+config.get('pachube', 'feedID')+'.csv?_method=put', sys.argv[1])
else:
	request = urllib2.Request('http://www.pachube.com/api/'+config.get('pachube', 'feedID')+'.csv?_method=put', sys.stdin.readline().rstrip('\n'))
request.add_header('Host','www.pachube.com')
request.add_header('X-PachubeApiKey', config.get('pachube', 'apiKey'))
url = opener.open(request)
